### ISSUE TITLE
Unhandled Exception - "Cannot read resources that depend on serialization"

### ISSUE THREAD

**Issue by AlternisDim20** [Nifyr/Imposters-Ordeal#4]
I downloaded v2.9.0 of Imposters Ordeal, since I had heard it was a great all-round tool for editing BDSP (rather than having to unpack and repack masterdatas and personal_masterdatas, and edit the .json files manually).

I also have my digital copy of BD, and dumped the romfs using nxdumptool.

Yet whenever I try to load my BD romfs in Imposters, an error box pops up - "Unhandled exception has occurred in your application...Cannot read resources that depend on serialization". 
The following details are also included: 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NotSupportedException: Cannot read resources that depend on serialization.
   at System.Resources.Extensions.DeserializingResourceReader.FindType(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at ImpostersOrdeal.LoadingForm.InitializeComponent() in C:\Users\ninte\source\repos\Imposters-Ordeal\Forms\LoadingForm.Designer.cs:line 73
   at ImpostersOrdeal.LoadingForm..ctor(String mainTask, String subTask) in C:\Users\ninte\source\repos\Imposters-Ordeal\Forms\LoadingForm.cs:line 20
   at ImpostersOrdeal.MainForm.MainForm_Load(Object sender, EventArgs e) in C:\Users\ninte\source\repos\Imposters-Ordeal\Forms\MainForm.cs:line 259
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Private.CoreLib.dll
----------------------------------------
Imposter's Ordeal
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/ninte/Downloads/Imposters.Ordeal.v2.9.0%20(1)/net5.0-windows/Imposter's%20Ordeal.dll
----------------------------------------
System.Runtime
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 5.0.1.0
    Win32 Version: 5.0.120.57506
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 5.0.1.0
    Win32 Version: 5.0.120.57506
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 5.0.120.57506
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.Extensions.dll
----------------------------------------
System.Linq
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Linq.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Memory
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Memory.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Resources.Extensions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/netstandard.dll
----------------------------------------
System.Drawing
    Assembly Version: 5.0.1.0
    Win32 Version: 5.0.120.57506
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Drawing.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ObjectModel.dll
----------------------------------------
System.Buffers
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Buffers.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ComponentModel.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.NonGeneric.dll
----------------------------------------
System.Data.Common
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Private.Xml.dll
----------------------------------------
AssetsTools.NET
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Users/ninte/Downloads/Imposters.Ordeal.v2.9.0%20(1)/net5.0-windows/AssetsTools.NET.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Private.Uri.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.Concurrent.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.IO.FileSystem.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.IO.MemoryMappedFiles.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.120.57516
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Text.Encoding.Extensions.dll
----------------------------------------

************** JIT Debugging **************
```

So...yeah. Not sure why. I redownloaded v2.9.0 of Imposters, and I redumped BD, yet this error always occurs.

**Comment by Nifyr** [comment]
Seems there was a bug with how certain icons were loaded. Fixed in latest release. If this still does not work for you, try earlier releases.

**Comment by AlternisDim20** [comment]
That worked; thanks.
